<p>Name: Md Faruk Ahmed Shipon&nbsp;</p>
<p>Father's Name: Md Ismile Hossen</p>
<p>Mother&rsquo;s Name: Mrs Amena Begum&nbsp;</p>
<p>Permanent Address: Vill- Birvodro, Post-Mahiganj</p>
<p>&nbsp;Thana- Mahiganj, District- Rangpur.</p>
<p>Present Address: Vill- Birvodro, Post-Mahiganj</p>
<p>&nbsp;Thana- Mahiganj, District- Rangpur.</p>
<p>Nationality: Bangladesh&nbsp;</p>
<p>Religion: Islam</p>
<p>Contact: 017***</p>
<p>Marital Status : Married</p>
<p>Blood Group: A+</p>
<p>Educational Qualification:&nbsp;</p>
<p>M.A&nbsp;</p>
<p>English</p>
<p>BRUR</p>
<p>1ST CLASS&nbsp;</p>
<p>2025</p>
<p>B.A&nbsp;</p>
<p>English&nbsp;</p>
<p>BRUR</p>
<p>1ST CLASS&nbsp;</p>
<p>2024</p>
<p><br /><br /></p>
<p>H.S.C&nbsp;</p>
<p>SCIENCE&nbsp;</p>
<p>DINAJPUR&nbsp;</p>
<p>CHARMICHAL COLLEGE&nbsp;</p>
<p>3.75</p>
<p>2018</p>
<p>S.S.C&nbsp;</p>
<p>SCIENCE&nbsp;</p>
<p>DINAJPUR&nbsp;</p>
<p>5.00</p>
<p>2016</p>
<p><br /><br /><br /></p>
